name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: xmlwriter

    - name: Install dependencies
      run: |
        make install
        bin/composer require --dev "phpmd/phpmd=@stable"
        bin/composer require --dev phpstan/phpstan

    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.1
        path: lib/
        standard: phpcs.xml

    - name: Run PHPMD
      run: ./vendor/bin/phpmd ./lib ansi codesize,unusedcode,naming 

    - name: Run PHPSTAN
      run: ./vendor/bin/phpstan analyse lib

    - name: Test
      run: ./vendor/bin/phpunit --coverage-cobertura=coverage.cobertura.xml
      
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
        
    - name: Exporting coverage to action summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
